### ISSUE TITLE
Example Documents

### ISSUE THREAD

**Issue by hahsan-ti** [vitg-gsa-automation/chkschema#1]
Can you please provide examples of **correct** and **incorret** documents as samples for this schema checker?

**Comment by vitggsa** [comment]
Attached are some example SSPs (one that validates and one that does not)

You can also find FedRAMP specific example documents from GSA FedRAMP for OSCAL at the following URL:
https://github.com/GSA/fedramp-automation/tree/master/dist/content/rev4/templates/ssp/xml  (for a larger System Security Plan example that validates).

[AweSomeSSP.zip](https://github.com/vitg-gsa-automation/chkschema/files/10688388/AweSomeSSP.zip)
